########################################
#Small Animal PET simulation program
# version 1.4 17-06-2015
# @ Nikos Efthimiou
########################################
#	A D D E R
/gate/digitizer/Singles/insert adder


#       R E A D O U T 
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeEnergyWinner
/gate/digitizer/Singles/readout/setDepth 3

#      E N E R G Y   B L U R R I N G
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.11
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV

#       E N E R G Y   C U T
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 300. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 700. keV

# 	T I M E  R E S O L U T I O N
/gate/digitizer/Singles/insert timeResolution 
/gate/digitizer/Singles/timeResolution/setTimeResolution 35.35 ps 

#	C O I N C I    S O R T E R 
/gate/digitizer/Coincidences/setWindow 4.5 ns
/gate/digitizer/Coincidences/minSectorDifference 186
