#
#       P H Y S I C S
#
#/gate/physics/addProcess PhotoElectric
#/gate/physics/processes/PhotoElectric/setModel StandardModel
#
#/gate/physics/addProcess Compton
#/gate/physics/processes/Compton/setModel StandardModel
#
#/gate/physics/addProcess RayleighScattering
#/gate/physics/processes/RayleighScattering/setModel LivermoreModel
#
#/gate/physics/addProcess ElectronIonisation
#/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
#/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
#
#/gate/physics/addProcess Bremsstrahlung
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+
#
#/gate/physics/addProcess PositronAnnihilation
#
#/gate/physics/addProcess eMultipleScattering
#/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
#/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/addPhysicsList emstandard_opt3
# /gate/physics/addProcess DecayPhysics
/gate/physics/addProcess RadioactiveDecay

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#
#       C U T S
#
# Cuts for particles
/gate/physics/Gamma/SetCutInRegion      world 100 um
/gate/physics/Electron/SetCutInRegion   world 100 um
/gate/physics/Positron/SetCutInRegion   world 100 um
