/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeEnergyWinner
/gate/digitizer/Singles/readout/setDepth 2

/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 300. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 700. keV

/gate/digitizer/name Coincidences
/gate/digitizer/insert coincidenceSorter
/gate/digitizer/Coincidences/setWindow 0.1 ns
/gate/digitizer/Coincidences/minSectorDifference 1

/gate/digitizer/Coincidences/MultiplesPolicy takeAllGoods
