/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeEnergyWinner
/gate/digitizer/Singles/readout/setDepth 2


#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#                       O P T I O N   [A]    - Aborted -          #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#MultTimeResolution - Obsolete I think was not a great idea. 
#/gate/digitizer/Singles/insert multTimeResolution 
#/gate/digitizer/Singles/multTimeResolution/setMultTimeResolution_1 50 ps
#/gate/digitizer/Singles/multTimeResolution/setMultTimeResolution_2 60 ps
#/gate/digitizer/Singles/multTimeResolution/setMultTimeResolution_3 100 ps

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#                       O P T I O N   [B]                         #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Insert as many timeResolution modules as needed defining each time the target 
# volume name. Similar to the _deadtime_ module. The medium speed pulses will 
# be created automatically by combining the two time resolutions

/gate/digitizer/Singles/insert timeResolution 
# 130 / sqrt(2) 
/gate/digitizer/Singles/timeResolution/setTimeResolution 91.92 ps
/gate/digitizer/Singles/timeResolution/chooseDTVolume LYSO_cry 

/gate/digitizer/Singles/insert timeResolution
# 50 / sqrt(2)
/gate/digitizer/Singles/timeResolution/setTimeResolution 35.35 ps
/gate/digitizer/Singles/timeResolution/chooseDTVolume Plastic_cry

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 300. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 700. keV

/gate/digitizer/name Coincidences
/gate/digitizer/insert coincidenceSorter
/gate/digitizer/Coincidences/setWindow 0.1 ns
/gate/digitizer/Coincidences/minSectorDifference 1

/gate/digitizer/Coincidences/MultiplesPolicy takeAllGoods
