# By default the adder is only applied at the lowest
# level. We have to move that in the module. 
/gate/digitizer/Singles/insert adder
#/gate/digitizer/Singles/adder/setDepth 3

#
# The energy resolution should be set before the readout. - Maybe 
#
/gate/digitizer/Singles/insert blurring 
/gate/digitizer/Singles/blurring/setResolution 0.11
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV

/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setPolicy TakeLayerWinner
# The module is one meta-crystal
/gate/digitizer/Singles/readout/setDepth 2
/gate/digitizer/Singles/readout/setWinningEnergy 0.100 keV
/gate/digitizer/Singles/readout/setLayerName Plastic_cry


#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#              M O D U L A R    T H R E S H O L D E R             #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#/gate/digitizer/Singles/name thresholderLYSO
#/gate/digitizer/Singles/insert thresholder
#/gate/digitizer/Singles/thresholderLYSO/setThreshold 300. keV
#/gate/digitizer/Singles/thresholderLYSO/chooseTHVolume LYSO_cry 

#/gate/digitizer/Singles/name thresholderPlastic
#/gate/digitizer/Singles/insert thresholder
#/gate/digitizer/Singles/thresholderPlastic/setThreshold 10. keV
#/gate/digitizer/Singles/thresholderPlastic/chooseTHVolume Plastic_cry 


/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 450. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 650. keV

## TODO: Fix Energy resolution to be per layer. 

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#                       O P T I O N   [A]    - Aborted -          #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#MultTimeResolution - Obsolete I think was not a great idea. 
#/gate/digitizer/Singles/insert multTimeResolution 
#/gate/digitizer/Singles/multTimeResolution/setMultTimeResolution_1 50 ps
#/gate/digitizer/Singles/multTimeResolution/setMultTimeResolution_2 60 ps
#/gate/digitizer/Singles/multTimeResolution/setMultTimeResolution_3 100 ps

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#                       O P T I O N   [B]                         #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Insert as many timeResolution modules as needed defining each time the target 
# volume name. Similar to the _deadtime_ module. The medium speed pulses will 
# be created automatically by combining the two time resolutions

/gate/digitizer/Singles/name timeResolutionLYSO
/gate/digitizer/Singles/insert timeResolution 
# 130 / sqrt(2) 
/gate/digitizer/Singles/timeResolutionLYSO/setTimeResolution 91.92 ps
/gate/digitizer/Singles/timeResolutionLYSO/chooseTRVolume LYSO_cry 

/gate/digitizer/Singles/name timeResolutionPlastic
/gate/digitizer/Singles/insert timeResolution
# 50 / sqrt(2)
/gate/digitizer/Singles/timeResolutionPlastic/setTimeResolution 35.35 ps
/gate/digitizer/Singles/timeResolutionPlastic/chooseTRVolume Plastic_cry

#-------------------oooooOOOOO00000OOOOOooooo---------------------#




#/gate/digitizer/name Coincidences
#/gate/digitizer/insert coincidenceSorter
/gate/digitizer/Coincidences/setWindow 4.5 ns
/gate/digitizer/Coincidences/minSectorDifference 186

#/gate/digitizer/Coincidences/MultiplesPolicy takeAllGoods
