# W O R L D
/gate/world/geometry/setXLength 120. cm
/gate/world/geometry/setYLength 120. cm
/gate/world/geometry/setZLength 120. cm
/gate/world/setMaterial Air
/gate/world/vis/forceWireframe
/gate/world/vis/setColor white


# SET type of PET system and dimensions
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/geometry/setRmax 480 mm
/gate/cylindricalPET/geometry/setRmin 450 mm
/gate/cylindricalPET/geometry/setHeight 150 mm
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setVisible 1

# R S E C T O R
/gate/cylindricalPET/daughters/name rsector
/gate/cylindricalPET/daughters/insert box
/gate/rsector/geometry/setXLength 15 mm
/gate/rsector/geometry/setYLength 3.2 mm
/gate/rsector/geometry/setZLength 150.4 mm
/gate/rsector/placement/setTranslation 457.5 0 0 mm
/gate/rsector/setMaterial Air
/gate/rsector/vis/forceWireframe
/gate/rsector/vis/setColor green
/gate/rsector/vis/setVisible 1

# M O D U L E
/gate/rsector/daughters/name module
/gate/rsector/daughters/insert box
/gate/module/geometry/setXLength 15. mm
/gate/module/geometry/setYLength 3.2 mm
/gate/module/geometry/setZLength 3.2 mm
/gate/module/setMaterial Air
/gate/module/vis/forceWireframe
/gate/module/vis/setColor gray
/gate/module/vis/setVisible 0

# S U B M O D U L E
/gate/module/daughters/name submodule
/gate/module/daughters/insert box
/gate/submodule/geometry/setXLength 15. mm
/gate/submodule/geometry/setYLength 3.2 mm
/gate/submodule/geometry/setZLength 3.2 mm
/gate/submodule/setMaterial Air
/gate/submodule/vis/forceWireframe
/gate/submodule/vis/setColor blue
/gate/submodule/vis/setVisible 0

# C R Y S T A L
/gate/submodule/daughters/name crystal
/gate/submodule/daughters/insert box
/gate/crystal/geometry/setXLength 15. mm
/gate/crystal/geometry/setYLength 0.4 mm
/gate/crystal/geometry/setZLength 3.2 mm
/gate/crystal/setMaterial Air
/gate/crystal/vis/forceWireframe
/gate/crystal/vis/setColor magenta
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/vis/setVisible 0

# L A Y E R (s)
/gate/crystal/daughters/name LYSO
/gate/crystal/daughters/insert box
/gate/LYSO/geometry/setXLength 15. mm
/gate/LYSO/geometry/setYLength 0.2 mm
/gate/LYSO/geometry/setZLength 3.2 mm
/gate/LYSO/placement/setTranslation 0 0.1 0 mm
/gate/LYSO/setMaterial LYSO
# /gate/LYSO/vis/forceWireframe
/gate/LYSO/vis/setColor yellow
/gate/LYSO/vis/setVisible 0

/gate/crystal/daughters/name Plastic
/gate/crystal/daughters/insert box
/gate/Plastic/geometry/setXLength 15. mm
/gate/Plastic/geometry/setYLength 0.2 mm
/gate/Plastic/geometry/setZLength 3.2 mm
/gate/Plastic/placement/setTranslation 0 -0.1 0 mm
/gate/Plastic/setMaterial Plastic
# /gate/Plastic/vis/forceWireframe
/gate/Plastic/vis/setColor cyan
/gate/Plastic/vis/setVisible 0


# R E P E A T C R Y S T A L
/gate/crystal/cubicArray/setRepeatNumberY 8
/gate/crystal/cubicArray/setRepeatNumberZ 1
/gate/crystal/cubicArray/setRepeatVector 0. 0.4 0 mm

# R E P E A T M O D U L E
/gate/module/repeaters/insert cubicArray
/gate/module/cubicArray/setRepeatNumberZ 47
/gate/module/cubicArray/setRepeatNumberY 1
/gate/module/cubicArray/setRepeatVector 0. 0 3.2 mm

# R E P E A T R S E C T O R
/gate/rsector/repeaters/insert ring
# /gate/rsector/ring/setRepeatNumber 1
/gate/rsector/ring/setRepeatNumber 883


# S O U R C E S
# sources will be embedded in a cylinder
# as large as the FOV, and longer in z (in case a source longer than the scanner is needed )
# this cylinder is created in case the sources need to be rotated
/gate/world/daughters/name cylinderSource
/gate/world/daughters/insert cylinder
/gate/cylinderSource/setMaterial Air
/gate/cylinderSource/geometry/setRmax 450 mm
/gate/cylinderSource/geometry/setHeight 300 mm
/gate/cylinderSource/vis/setColor blue
/gate/cylinderSource/vis/forceWireframe
/gate/cylinderSource/vis/setVisible 1

# /gate/world/geometry/setXLength 120. cm
# /gate/world/geometry/setYLength 120. cm
# /gate/world/geometry/setZLength 120. cm
# /gate/world/setMaterial Air
# /gate/world/vis/forceWireframe
# /gate/world/vis/setColor white
#
#
# # geometry like newclearpem
# /gate/world/daughters/name cylindricalPET
# /gate/world/daughters/insert cylinder
# /gate/cylindricalPET/setMaterial Vacuum
# /gate/cylindricalPET/geometry/setRmax 380 mm
# /gate/cylindricalPET/geometry/setRmin 350 mm
#
#
# /gate/cylindricalPET/geometry/setHeight 256 mm
# /gate/cylindricalPET/vis/forceWireframe
# /gate/cylindricalPET/vis/setVisible 1
#
# # R S E C T O R
# /gate/cylindricalPET/daughters/name rsector
# /gate/cylindricalPET/daughters/insert box
#
# /gate/rsector/placement/setTranslation 360. 0 0 mm
# /gate/rsector/geometry/setXLength 20. mm
# /gate/rsector/geometry/setYLength 16 mm
# /gate/rsector/geometry/setZLength 256 mm
# /gate/rsector/setMaterial Air
# /gate/rsector/vis/forceWireframe
# /gate/rsector/vis/setColor green
# /gate/rsector/vis/setVisible 1
#
# # M O D U L E
# /gate/rsector/daughters/name module
# /gate/rsector/daughters/insert box
# /gate/module/geometry/setXLength 20. mm
# /gate/module/geometry/setYLength 16. mm
# /gate/module/geometry/setZLength 16. mm
# #temp material BaSO4 -> define Vikuiti
# /gate/module/setMaterial BaSO4
# /gate/module/vis/forceWireframe
# /gate/module/vis/setColor gray
# /gate/module/vis/setVisible 1
#
#
# # S U B M O D U L E
# /gate/module/daughters/name submodule
# /gate/module/daughters/insert box
# /gate/submodule/geometry/setXLength 20. mm
# /gate/submodule/geometry/setYLength 8. mm
# /gate/submodule/geometry/setZLength 8. mm
# #temp material BaSO4 -> define Vikuiti
# /gate/submodule/setMaterial BaSO4
# /gate/submodule/vis/forceWireframe
# /gate/submodule/vis/setColor green
# /gate/submodule/vis/setVisible 1
#
# # C R Y S T A L
# /gate/submodule/daughters/name crystal
# /gate/submodule/daughters/insert box
# /gate/crystal/geometry/setXLength 20. mm
# /gate/crystal/geometry/setYLength 3.8 mm
# /gate/crystal/geometry/setZLength 3.8 mm
# #temp material LSO -> define LYSO
# /gate/crystal/setMaterial LSO
# /gate/crystal/vis/forceWireframe
# /gate/crystal/vis/setColor magenta
# /gate/crystal/repeaters/insert cubicArray
# /gate/crystal/vis/setVisible 1
#
#
# # L A Y E R
# /gate/crystal/daughters/name LSO
# /gate/crystal/daughters/insert box
# /gate/LSO/geometry/setXLength 20. mm
# /gate/LSO/geometry/setYLength 3.8 mm
# /gate/LSO/geometry/setZLength 3.8 mm
# /gate/LSO/placement/setTranslation 0 0 0 mm
# /gate/LSO/setMaterial LSO
# /gate/LSO/vis/setColor yellow
# /gate/LSO/vis/setVisible 0
#
# # R E P E A T C R Y S T A L
# /gate/crystal/cubicArray/setRepeatNumberY 2
# /gate/crystal/cubicArray/setRepeatNumberZ 2
# /gate/crystal/cubicArray/setRepeatVector 0. 4.0 4.0 mm
#
# # R E P E A T S U B M O D U L E
# /gate/submodule/repeaters/insert cubicArray
# /gate/submodule/cubicArray/setRepeatNumberY 2
# /gate/submodule/cubicArray/setRepeatNumberZ 2
# /gate/submodule/cubicArray/setRepeatVector 0. 8. 8. mm
#
# # R E P E A T M O D U L E
# /gate/module/repeaters/insert cubicArray
# /gate/module/cubicArray/setRepeatNumberZ 16
# /gate/module/cubicArray/setRepeatNumberY 1
# /gate/module/cubicArray/setRepeatVector 0. 16. 16. mm
#
# # R E P E A T R S E C T O R
# /gate/rsector/repeaters/insert ring
# #/gate/rsector/ring/setRepeatNumber 48
# /gate/rsector/ring/setRepeatNumber 137
#
# # S O U R C E S
# # will be embedded in a cylinder
# /gate/world/daughters/name cylinderSource
# /gate/world/daughters/insert cylinder
# /gate/cylinderSource/setMaterial Vacuum
# /gate/cylinderSource/geometry/setRmax 250 mm
# /gate/cylinderSource/geometry/setHeight 256 mm
# #/gate/cylinderSource/vis/setColor blue
# /gate/cylinderSource/vis/forceWireframe
# /gate/cylinderSource/vis/setVisible 1
